defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "no_fenced_code_blocks", "autolink", "strikethrough", "superscript"]