defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis",  "fenced_code_blocks", "autolink", "strikethrough", "superscript"]